export { default as onBranchContextMenu } from './branch-menu'
export { default as onTagContextMenu } from './tag-menu'
export { default as onGitLogContextMenu } from './gitlog-menu'
export { default as onChangedFileContextMenu } from './changedfiles-menu'
export { default as onStagedFileContextMenu } from './stagedfiles-menu'
export { default as onRemoteContextMenu } from './remote-menu'
